#!/bin/bash

comsolPath="/Applications/COMSOL54/Multiphysics"
javaFile="examples/from_dxf/test_device.java"

echo $PWD

javac -d . -cp "$comsolPath/plugins/*" -source 8 -target 8 src/*
javac -cp "$comsolPath/plugins/*":"." -source 8 -target 8 $javaFile
jar -cvf comsolbuilder.jar comsolbuilder/*
$comsolPath/bin/comsol batch -dev $PWD/comsolbuilder.jar -inputfile $PWD/${javaFile::${#javaFile}-5}.class -outputfile $PWD/${javaFile::${#javaFile}-5}.mph

rm -r comsolbuilder
rm ${javaFile::${#javaFile}-5}.class
rm comsolbuilder.jar
